let productsPicks = [
  {
    title: "PYTHON OBJECT ORIENTED PROGRAMMING",
    name: "python object oriented programming for beginers",
    by: "By:Kethrin",
    date: "19th September 2020",
    video: "https://youtu.be/ka6-_RfR9XA",
    link: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS",
    time: 500,
    price: 1500,
  },
  {
    title: "LEARN MS EXCEL",
    name: "MS excel for beginer to advance",
    by: "By:shekher",
    date: "19th August 2021",
    video: "https://youtu.be/w3aS2J2SMgI",
    link: "https://www.javatpoint.com/excel-tutorial",
    time: 4000,
    price: 400,
  },
  {
    title: "ASVANCE SQL FOR DATA SCIENTISTS",
    name: "Be an expert in sql learn advance sql in depth",
    by: "By:Saroj yadav",
    date: "03th july 2021",
    video: "https://youtu.be/exxnrj0_5QY",
    link: "https://www.simplilearn.com/tutorials/sql-tutorial/sql-advanced",
    time: 10000,
    price: 6000,
  },
  {
    title: "LEARNING DJANGO",
    name: "Django framework for intermidiate",
    by: "By:Paul Johnson",
    date: "19th March 2017",
    video: "https://youtu.be/Q_YOYNiSVDY",
    link: "https://docs.djangoproject.com/en/3.2/",
    time: 3000,
    price: 3999,
  },
  {
    title: "MEDIA QUERIES",
    name: "Create responsive pages using css media queries",
    by: "By:Ashish Mehra",
    date: "04th june 2019",
    video: "https://youtu.be/XAchqU1-PWI",
    link: "https://docs.djangoproject.com/en/3.2/",
    time: 300,
    price: 399,
  },
  {
    title: "ASYNC AND AWAITS",
    name: "Learn promies be expert in async and awaits ",
    by: "By:Shivani Chaudhari",
    date: "01th January 2018",
    video: "https://youtu.be/1aajQ-NCLDQ",
    link: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await",
    time: 350,
    price: 490,
  },
  {
    title: "LEARN FIGMA",
    name: "Create and design your own first website ",
    by: "By:Tejasvi Singh",
    date: "09th april 2013",
    video: "https://youtu.be/v_F0E1HAoYQ",
    link: "https://mockitt.wondershare.com/figma/figma-tutorial.html",
    time: 600,
    price: 999,
  },
  {
    title: "REACT:BUILD PROGRESSIVE WEB APPS",
    name: "Create and design your own first website ",
    by: "By:shekhar",
    date: "09th may 2018",
    video: "https://youtu.be/XOzKMdMNBRo",
    link: "https://www.tutorialspoint.com/react_native/react_native_overview.htm",
    time: 4500,
    price: 5999,
  },
  {
    title: "DATA STRUUCTURE AND ALGORITHM",
    name: "Be a pro in data structures and algorithms",
    by: "By:Abdul Bari",
    date: "09th october 2020",
    video: "https://youtu.be/X_i7FsClpOU",
    link: "https://www.geeksforgeeks.org/data-structures/",
    time: 8000,
    price: 10000,
  },
  {
    title: "DOCKER FOR DEVELOPERS",
    name: "Docker for develpers ",
    by: "By:Peter Dakota ",
    date: "28th February 2020",
    video: "https://youtu.be/KNkAm0l6wzA",
    link: "https://developer.mozilla.org/en-US/docs/Mozilla/QA/Running_automated_tests/Docker",
    time: 3000,
    price: 9550,
  },
  {
    title: "APTITUDE AND  REASONING ",
    name: "Learn aptitude and reasoning to crack the GATE ",
    by: "By:Swastika Mukharjee",
    date: "09th may 2018",
    video: "https://youtu.be/AFh1-fqdaf4",
    link: "https://developer.mozilla.org/en-US/docs/Mozilla/QA/Running_automated_tests/Docker",
    time: 780,
    price: 450,
  },
  {
    title: "HTML AND CSS FOR BEGINNERS LEVEL",
    name: "create atractive ui by using html and css ",
    by: "By:Viraat sharma",
    date: "21th Februay 2014",
    video: "https://youtu.be/0V86AiLV8HY",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    time: 788,
    price: 900,
  },
];
